// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models
{
    public partial class Admins
    {
        public int IdAdmin { get; set; }
        public int IdUser { get; set; }
        public int AdminType { get; set; }

        public virtual UserTypes AdminTypeNavigation { get; set; }
        public virtual Users IdUserNavigation { get; set; }
    }
}