// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models
{
    public partial class CropTypes
    {
        public CropTypes()
        {
            Plantings = new HashSet<Plantings>();
        }

        public int IdCrop { get; set; }
        public string CropType { get; set; }

        public virtual ICollection<Plantings> Plantings { get; set; }
    }
}