// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Models.Models
{
    public partial class FarmAdministratorContext : DbContext
    {
        public FarmAdministratorContext()
        {
        }

        public FarmAdministratorContext(DbContextOptions<FarmAdministratorContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Applications> Applications { get; set; }
        public virtual DbSet<Harvests> Harvests { get; set; }
        public virtual DbSet<Plantings> Plantings { get; set; }
        public virtual DbSet<Plots> Plots { get; set; }
        public virtual DbSet<Tokens> Tokens { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Weather> Weather { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Admins>(entity =>
            {
                entity.HasKey(e => e.IdAdmin);

                entity.Property(e => e.IdAdmin).HasColumnName("Id_Admin");

                entity.Property(e => e.IdUser).HasColumnName("Id_User");

                entity.HasOne(d => d.IdUserNavigation)
                    .WithMany(p => p.Admins)
                    .HasForeignKey(d => d.IdUser)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("Admins_Users");
            });

            modelBuilder.Entity<Applications>(entity =>
            {
                entity.HasKey(e => e.IdApplication);

                entity.Property(e => e.IdApplication).HasColumnName("id_application");

                entity.Property(e => e.Brand)
                    .HasMaxLength(255)
                    .HasColumnName("brand");

                entity.Property(e => e.Cost)
                    .HasColumnType("decimal(18, 0)")
                    .HasColumnName("cost");

                entity.Property(e => e.CropType)
                    .HasMaxLength(255)
                    .HasColumnName("crop_type");

                entity.Property(e => e.Dose).HasColumnName("dose");

                entity.Property(e => e.EndDate)
                    .HasColumnType("date")
                    .HasColumnName("end_date");

                entity.Property(e => e.IdPlot).HasColumnName("id_plot");

                entity.Property(e => e.Method)
                    .HasMaxLength(255)
                    .HasColumnName("method");

                entity.Property(e => e.Notes).HasColumnName("notes");

                entity.Property(e => e.ProductType)
                    .HasMaxLength(255)
                    .HasColumnName("product_type");

                entity.Property(e => e.StartDate)
                    .HasColumnType("date")
                    .HasColumnName("start_date");

                entity.HasOne(d => d.IdPlotNavigation)
                    .WithMany(p => p.Applications)
                    .HasForeignKey(d => d.IdPlot)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Applications_Plots");
            });

            modelBuilder.Entity<Harvests>(entity =>
            {
                entity.HasKey(e => e.IdHarvest)
                    .HasName("PK_Harvest");

                entity.Property(e => e.IdHarvest).HasColumnName("id_harvest");

                entity.Property(e => e.Cost)
                    .HasColumnType("decimal(18, 0)")
                    .HasColumnName("cost");

                entity.Property(e => e.Crop).HasColumnName("crop");

                entity.Property(e => e.EndDate)
                    .HasColumnType("date")
                    .HasColumnName("end_date");

                entity.Property(e => e.IdPlanting).HasColumnName("id_planting");

                entity.Property(e => e.IdPlot).HasColumnName("id_plot");

                entity.Property(e => e.Method)
                    .HasMaxLength(255)
                    .HasColumnName("method");

                entity.Property(e => e.Notes).HasColumnName("notes");

                entity.Property(e => e.Ripeness)
                    .HasMaxLength(255)
                    .HasColumnName("ripeness");

                entity.Property(e => e.Season)
                    .HasMaxLength(255)
                    .HasColumnName("season");

                entity.Property(e => e.Size).HasColumnName("size");

                entity.Property(e => e.StartDate)
                    .HasColumnType("date")
                    .HasColumnName("start_date");

                entity.Property(e => e.Yield).HasColumnName("yield");

                entity.HasOne(d => d.IdPlotNavigation)
                    .WithMany(p => p.Harvests)
                    .HasForeignKey(d => d.IdPlot)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Harvests_Plots");
            });

            modelBuilder.Entity<Plantings>(entity =>
            {
                entity.HasKey(e => e.IdPlanting)
                    .HasName("PK_Planting");

                entity.Property(e => e.IdPlanting).HasColumnName("id_planting");

                entity.Property(e => e.Cost)
                    .HasColumnType("decimal(18, 0)")
                    .HasColumnName("cost");

                entity.Property(e => e.Crop).HasColumnName("crop");

                entity.Property(e => e.Deep).HasColumnName("deep");

                entity.Property(e => e.Distance)
                    .HasMaxLength(10)
                    .HasColumnName("distance")
                    .IsFixedLength();

                entity.Property(e => e.EndDate)
                    .HasColumnType("date")
                    .HasColumnName("end_date");

                entity.Property(e => e.IdPlot).HasColumnName("id_plot");

                entity.Property(e => e.Season)
                    .HasMaxLength(255)
                    .HasColumnName("season");

                entity.Property(e => e.Size).HasColumnName("size");

                entity.Property(e => e.StartDate)
                    .HasColumnType("date")
                    .HasColumnName("start_date");

                entity.HasOne(d => d.IdPlotNavigation)
                    .WithMany(p => p.Plantings)
                    .HasForeignKey(d => d.IdPlot)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Plantings_Plots");
            });

            modelBuilder.Entity<Plots>(entity =>
            {
                entity.HasKey(e => e.IdPlot)
                    .HasName("PK_Plot");

                entity.Property(e => e.IdPlot).HasColumnName("id_plot");

                entity.Property(e => e.GroundType).HasColumnName("ground_type");

                entity.Property(e => e.IdUser).HasColumnName("id_user");

                entity.Property(e => e.Notes).HasColumnName("notes");

                entity.Property(e => e.Owner)
                    .HasMaxLength(255)
                    .HasColumnName("owner");

                entity.Property(e => e.PlotName)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("plot_name");

                entity.Property(e => e.Size).HasColumnName("size");

                entity.Property(e => e.State).HasColumnName("state");

                entity.HasOne(d => d.IdUserNavigation)
                    .WithMany(p => p.Plots)
                    .HasForeignKey(d => d.IdUser)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Plots_Users");
            });

            modelBuilder.Entity<Tokens>(entity =>
            {
                entity.HasKey(e => e.Token);

                entity.Property(e => e.Token).HasMaxLength(255);

                entity.Property(e => e.ExpirationDate)
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnName("Expiration_Date");

                entity.Property(e => e.GenerationDate)
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnName("Generation_Date");

                entity.Property(e => e.IdUser).HasColumnName("Id_User");

                entity.HasOne(d => d.IdUserNavigation)
                    .WithMany(p => p.Tokens)
                    .HasForeignKey(d => d.IdUser)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("Tokens_Users");
            });

            modelBuilder.Entity<Users>(entity =>
            {
                entity.HasKey(e => e.IdUser);

                entity.Property(e => e.IdUser).HasColumnName("id_user");

                entity.Property(e => e.Adress)
                    .HasMaxLength(255)
                    .HasColumnName("adress");

                entity.Property(e => e.Education).HasColumnName("education");

                entity.Property(e => e.Email)
                    .HasMaxLength(255)
                    .HasColumnName("email");

                entity.Property(e => e.Experience).HasColumnName("experience");

                entity.Property(e => e.LastName)
                    .HasMaxLength(255)
                    .HasColumnName("last_name");

                entity.Property(e => e.Name)
                    .HasMaxLength(255)
                    .HasColumnName("name");

                entity.Property(e => e.Password)
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnName("password");

                entity.Property(e => e.Phone).HasColumnName("phone");

                entity.Property(e => e.RegisterDate)
                    .HasColumnType("date")
                    .HasColumnName("register_date");

                entity.Property(e => e.State).HasColumnName("state");

                entity.Property(e => e.UserRole).HasColumnName("user_role");

                entity.Property(e => e.UserType).HasColumnName("user_type");
            });

            modelBuilder.Entity<Weather>(entity =>
            {
                entity.HasKey(e => e.IdWeather)
                    .HasName("PK_Weathers");

                entity.Property(e => e.IdWeather).HasColumnName("id_weather");

                entity.Property(e => e.Date)
                    .HasColumnType("date")
                    .HasColumnName("date");

                entity.Property(e => e.Hail).HasColumnName("hail");

                entity.Property(e => e.Humidity).HasColumnName("humidity");

                entity.Property(e => e.IdPlot).HasColumnName("id_plot");

                entity.Property(e => e.LastFrost)
                    .HasColumnType("date")
                    .HasColumnName("last_frost");

                entity.Property(e => e.MaxTemperature).HasColumnName("max_temperature");

                entity.Property(e => e.MinTemperature).HasColumnName("min_temperature");

                entity.Property(e => e.Precipitation).HasColumnName("precipitation");

                entity.Property(e => e.SoilMoisture).HasColumnName("soil_moisture");

                entity.Property(e => e.SunlightHours).HasColumnName("sunlight_hours");

                entity.Property(e => e.Wind).HasColumnName("wind");

                entity.HasOne(d => d.IdPlotNavigation)
                    .WithMany(p => p.Weather)
                    .HasForeignKey(d => d.IdPlot)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Weather_Plots");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}