// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models
{
    public partial class GroundTypes
    {
        public GroundTypes()
        {
            Plots = new HashSet<Plots>();
        }

        public int IdGroundType { get; set; }
        public string GroundType { get; set; }

        public virtual ICollection<Plots> Plots { get; set; }
    }
}