// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models
{
    public partial class Harvests
    {
        public int IdHarvest { get; set; }
        public int? IdPlanting { get; set; }
        public string Season { get; set; }
        public string Method { get; set; }
        public string Ripeness { get; set; }
        public int? Yield { get; set; }
        public string Notes { get; set; }
        public int? Size { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public decimal? Cost { get; set; }
        public int? IdCrop { get; set; }
        public int IdPlot { get; set; }

        public virtual CropTypes IdCropNavigation { get; set; }
        public virtual Plots IdPlotNavigation { get; set; }
    }
}