// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models
{
    public partial class HistoryFuelConsumption
    {
        public int IdRecord { get; set; }
        public int IdMachine { get; set; }
        public DateTime RecordDate { get; set; }
        public decimal LitersQuantity { get; set; }

        public virtual Machinery IdMachineNavigation { get; set; }
    }
}