// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models
{
    public partial class MachineUserRelationship
    {
        public int IdRelationship { get; set; }
        public int IdMachine { get; set; }
        public int IdUser { get; set; }
        public int RelationshipType { get; set; }

        public virtual Machinery IdMachineNavigation { get; set; }
        public virtual Users IdUserNavigation { get; set; }
    }
}