// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models
{
    public partial class Machinery
    {
        public Machinery()
        {
            HistoryFuelConsumption = new HashSet<HistoryFuelConsumption>();
            MachineUserRelationship = new HashSet<MachineUserRelationship>();
            MaintenanceRepairs = new HashSet<MaintenanceRepairs>();
        }

        public int IdMachine { get; set; }
        public string Name { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string MachineType { get; set; }
        public DateTime? YearManufactured { get; set; }
        public int? WorkingHours { get; set; }
        public int IdState { get; set; }
        public bool Isactive { get; set; }

        public virtual MachineryStateTypes IdStateNavigation { get; set; }
        public virtual ICollection<HistoryFuelConsumption> HistoryFuelConsumption { get; set; }
        public virtual ICollection<MachineUserRelationship> MachineUserRelationship { get; set; }
        public virtual ICollection<MaintenanceRepairs> MaintenanceRepairs { get; set; }
    }
}