// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models
{
    public partial class MachineryStateTypes
    {
        public MachineryStateTypes()
        {
            Machinery = new HashSet<Machinery>();
        }

        public int IdState { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Machinery> Machinery { get; set; }
    }
}