// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models
{
    public partial class MaintenanceRepairs
    {
        public int IdMaintenance { get; set; }
        public int IdMachine { get; set; }
        public DateTime Date { get; set; }
        public string Description { get; set; }
        public int? WorkedHours { get; set; }
        public string SparePartsUsed { get; set; }
        public decimal? Cost { get; set; }

        public virtual Machinery IdMachineNavigation { get; set; }
    }
}