// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models
{
    public partial class Plantings
    {
        public int IdPlanting { get; set; }
        public int Crop { get; set; }
        public string Season { get; set; }
        public int? Deep { get; set; }
        public string Distance { get; set; }
        public int? Size { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public decimal? Cost { get; set; }
        public int IdPlot { get; set; }

        public virtual CropTypes CropNavigation { get; set; }
        public virtual Plots IdPlotNavigation { get; set; }
    }
}