// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models
{
    public partial class PlotStateTypes
    {
        public PlotStateTypes()
        {
            Plots = new HashSet<Plots>();
        }

        public int IdState { get; set; }
        public string State { get; set; }

        public virtual ICollection<Plots> Plots { get; set; }
    }
}