// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models
{
    public partial class Plots
    {
        public Plots()
        {
            Applications = new HashSet<Applications>();
            Harvests = new HashSet<Harvests>();
            Plantings = new HashSet<Plantings>();
            Weather = new HashSet<Weather>();
        }

        public int IdPlot { get; set; }
        public string PlotName { get; set; }
        public int? Size { get; set; }
        public int? GroundType { get; set; }
        public string Owner { get; set; }
        public string Notes { get; set; }
        public int? State { get; set; }
        public int IdUser { get; set; }

        public virtual GroundTypes GroundTypeNavigation { get; set; }
        public virtual Users IdUserNavigation { get; set; }
        public virtual PlotStateTypes StateNavigation { get; set; }
        public virtual ICollection<Applications> Applications { get; set; }
        public virtual ICollection<Harvests> Harvests { get; set; }
        public virtual ICollection<Plantings> Plantings { get; set; }
        public virtual ICollection<Weather> Weather { get; set; }
    }
}