// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models
{
    public partial class ProductTypes
    {
        public int IdProductType { get; set; }
        public string ProductType { get; set; }
    }
}