// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models
{
    public partial class RoleTypes
    {
        public RoleTypes()
        {
            Users = new HashSet<Users>();
        }

        public int IdRoleType { get; set; }
        public string RoleType { get; set; }

        public virtual ICollection<Users> Users { get; set; }
    }
}