// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models
{
    public partial class Tokens
    {
        public string Token { get; set; }
        public int IdUser { get; set; }
        public string GenerationDate { get; set; }
        public string ExpirationDate { get; set; }
        public bool Valid { get; set; }

        public virtual Users IdUserNavigation { get; set; }
    }
}