// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models
{
    public partial class Users
    {
        public Users()
        {
            Admins = new HashSet<Admins>();
            Plots = new HashSet<Plots>();
            Tokens = new HashSet<Tokens>();
        }

        public int IdUser { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public int UserRole { get; set; }
        public int UserType { get; set; }
        public string Email { get; set; }
        public int? Phone { get; set; }
        public string Adress { get; set; }
        public string Experience { get; set; }
        public string Education { get; set; }
        public DateTime? RegisterDate { get; set; }
        public int State { get; set; }

        public virtual RoleTypes UserRoleNavigation { get; set; }
        public virtual UserTypes UserTypeNavigation { get; set; }
        public virtual ICollection<Admins> Admins { get; set; }
        public virtual ICollection<Plots> Plots { get; set; }
        public virtual ICollection<Tokens> Tokens { get; set; }
    }
}