// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models
{
    public partial class UserTypes
    {
        public UserTypes()
        {
            Admins = new HashSet<Admins>();
            Users = new HashSet<Users>();
        }

        public int IdUserType { get; set; }
        public string UserType { get; set; }

        public virtual ICollection<Admins> Admins { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}