// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models
{
    public partial class Weather
    {
        public int IdWeather { get; set; }
        public int? MinTemperature { get; set; }
        public int? MaxTemperature { get; set; }
        public int? Precipitation { get; set; }
        public int? SunlightHours { get; set; }
        public int? Humidity { get; set; }
        public int? Wind { get; set; }
        public DateTime? LastFrost { get; set; }
        public int? SoilMoisture { get; set; }
        public int? Hail { get; set; }
        public DateTime? Date { get; set; }
        public int IdPlot { get; set; }

        public virtual Plots IdPlotNavigation { get; set; }
    }
}